### ISSUE TITLE
Chaning Input sources in Mac

### ISSUE THREAD

**Issue by kimwoo-ya** [deskflow/deskflow#7832] opened 2024-10-30 13:22 UTC
### Feature Request

Hi.
I just want to know "is there any ways to solve my problem?"

My Env 
- Windows 11(Server) - deskflow_1.17.0.153
- Mac (Client) - deskflow_1.17.0.153

While Using deskflow, it doesn't go wrong changing Input source(english to other language) in Windows.
however I pressed capslock key several times to change Input source(english to other language) in Mac.
but It doesn't work at all.

I searched it and found similiar situation(https://github.com/deskflow/deskflow/issues/6830)

am I configured somthing wrong? or that feature that I tagged is still in progress? 

please let me know.
thank you.

**Comment by nbolton** [comment] 2024-10-30 16:55
I think this one of those "is this a bug or a missing feature" type issues. To me it looks like #6830 is the bug that you're referring to. Is there anything about that bug that doesn't line up with what you're not seeing or want to see?

**Comment by kimwoo-ya** [comment] 2024-10-31 06:28
> I think this one of those "is this a bug or a missing feature" type issues. To me it looks like #6830 is the bug that you're referring to. Is there anything about that bug that doesn't line up with what you're not seeing or want to see?

I agree with what you said. 
It is difficult to determine whether it is a missing feature or a bug. 
The description specified in the hyperlink matches my situation. 
thank you

**Comment by nbolton** [comment] 2024-10-31 09:10
> Is there any plan to fix this problem?

We plan to fix all open bugs, but we cannot say when.

> The description specified in the hyperlink matches my situation.

Ok, let's go ahead and close this as a duplicate of #6830.

**Closed by nbolton** 2024-10-31 09:10 UTC
Labels: enhancement, triage
