### ISSUE TITLE
openssl error: error:0A000126:SSL routines::unexpected eof while reading

### ISSUE THREAD

**Issue by optlee** [deskflow/deskflow#8021] opened 2024-12-30 12:39 UTC
### Project

Deskflow

### Deskflow version number

1.17.2.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [X] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [X] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

win10
macOS Monterey 12.7.3 (21H1015)

### Deskflow configuration

macOS Monterey 12.7.3 (21H1015) server
win10 client

### What steps will reproduce the problem?

After server & client are connected, use win+shift+s to print screen
the bug happened

### Log output

```shell
[2024-12-30T20:33:33] INFO: entering screen
[2024-12-30T20:33:33] ERROR: tls error occurred (generic failure)
[2024-12-30T20:33:33] ERROR: openssl error: error:0A000126:SSL routines::unexpected eof while reading
[2024-12-30T20:33:33] INFO: leaving screen
[2024-12-30T20:33:33] NOTE: disconnected from server
[2024-12-30T20:33:34] NOTE: connecting to '192.168.50.20': 192.168.50.20:24800
[2024-12-30T20:33:34] NOTE: server fingerprint: C7:30:B4:9F:56:0D:8F:EC:F9:10:72:6D:90:C1:16:C8:8F:C2:C6:27:2D:C6:66:9F:DA:1D:5F:23:52:68:05:76
[2024-12-30T20:33:34] INFO: connected to secure socket
[2024-12-30T20:33:34] INFO: server tls certificate info: /CN=Deskflow
[2024-12-30T20:33:34] INFO: network encryption protocol: TLSv1.3
[2024-12-30T20:33:34] INFO: local languages: zh
[2024-12-30T20:33:34] INFO: remote languages: en
[2024-12-30T20:33:34] WARNING: You need to install these languages on this computer and restart Deskflow to enable support for multiple languages: en
[2024-12-30T20:33:35] NOTE: connected to server
[2024-12-30T20:33:40] INFO: entering screen
[2024-12-30T20:33:40] INFO: clipboard was updated
[2024-12-30T20:33:40] INFO: clipboard was updated
[2024-12-30T20:34:03] WARNING: current server language is not installed on client
[2024-12-30T20:36:23] INFO: leaving screen
[2024-12-30T20:36:29] INFO: entering screen
[2024-12-30T20:36:30] INFO: clipboard was updated
[2024-12-30T20:36:30] INFO: clipboard was updated
[2024-12-30T20:36:31] INFO: leaving screen
[2024-12-30T20:36:33] INFO: entering screen
[2024-12-30T20:36:35] WARNING: current server lang
```

**Comment by sithlord48** [comment] 2024-12-30 12:43
Duplicate of #7853 , Please Track that Issue.

**Closed by sithlord48** 2024-12-30 12:43 UTC
Labels: bug, triage, unanswered
