### ISSUE TITLE
Windows error continuously shows ：failed to cd up to profile root dir

### ISSUE THREAD

**Issue by xiaohanbaofu** [deskflow/deskflow#7961] opened 2024-12-08 07:45 UTC
### Project

Deskflow

### Deskflow version number

1.17.2.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

- Windows11

**Comment by xiaohanbaofu** [comment] 2024-12-08 07:55
<img width="359" alt="image" src="https://github.com/user-attachments/assets/1b355904-899d-4c91-8a97-941d8bf493a1">

**Comment by sithlord48** [comment] 2024-12-08 15:36
may i ask what the dir path is ? does it contain non latin characters ?

**Comment by xiaohanbaofu** [comment] 2024-12-09 01:52
> Duplicate #7789
> 
> may i ask what the dir path is ? does it contain non latin characters ? If so try the build for this PR #7959 and let me know if that fixes the issue.

D:\deskflow

**Comment by xiaohanbaofu** [comment] 2024-12-09 02:20
> Duplicate #7789
> 
> may i ask what the dir path is ? does it contain non latin characters ? If so try the build for this PR #7959 and let me know if that fixes the issue.

done！

**Comment by sithlord48** [comment] 2024-12-09 02:36
What is the directory where deskflow is looking for your profile ? and did the other PR help ?

**Comment by sithlord48** [comment] 2024-12-20 17:56
Closing as duplicate of https://github.com/deskflow/deskflow/issues/7789

**Closed by sithlord48** 2024-12-20 17:56 UTC
Labels: bug
