### ISSUE TITLE
Conflict with “better and better” software

### ISSUE THREAD

**Issue by luantu** [deskflow/deskflow#7704] opened 2024-10-15 09:46 UTC
### Project

Deskflow

### Deskflow version number

1.17.0

### Build type

Deskflow package (downloaded from us)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other

### Wayland on Linux

- [ ] I have reviewed the Wayland known issues and my issue is new
- [X] I am not using Wayland on Linux

### Signing on macOS

- [X] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### OS versions/distros

MACOS 15.0.1

### Deskflow configuration

macos server and windows 11 client

### What steps will reproduce the problem?

1. install better and better https://www.better365.cn/bab2.html
2. enable Mouse Action gestures
3. When I right-click mouse on the client , the right-click will also occur on server side

**Comment by nbolton** [comment] 2024-10-15 15:29
I'm not sure we can support 3rd party software, sorry. The problem is that we're probably using the same library as the other app, and the OS APIs arent designed to be used like that. Unfortunately, you'll need to pick one.

@sithlord48 Think we should close as wont fix?

**Closed** 2024-10-15 17:55 UTC
Labels: bug, triage
