### ISSUE TITLE
Unicode bug: Fatal error on Windows 11

### ISSUE THREAD

**Issue by jamoram** [deskflow/deskflow#7876] opened 2024-11-08 22:30 UTC
### Project

Deskflow

### Deskflow version number

1.17.1.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [X] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [X] I am not using macOS

### Continuous build

- [X] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

Windows 11

### Deskflow configuration

-windows 11 server, linux kali client

### What steps will reproduce the problem?

1. Install Deskflow
2. configure the ip addes for the server
3. select the option of Use this computer's heboard and mouse

### Log output

```shell
v1.17.1.0 (a80cea3c)
failed to cd up to profile root dir
```

### Additional information

I was trying to use Input Leap, I unistall it and deleted manually all the registries. Then I install Deskflow on linux and work perfectly, When I install on windows get that error and them is imposible to open de application. If I want to try it again i have to unistall Deskflow and then delet all the registries to be able to install it again.

**Comment by nbolton** [comment] 2024-11-12 14:15
Could you let me know the full path of your user dir on your Windows computer? I'm wondering if it has unicode chars in it or something.

**Comment by jamoram** [comment] 2024-11-14 16:11
Hi, Sorry for my late answer, yes that is the problem my dir has a "é" character! that is why I have all those problems.  When I post it I was thinking that the issue #7789 was already fix for this types of character. At the end I create another user and install it with that user that hasn't have unicode chars.

**Comment by nbolton** [comment] 2024-11-15 13:04
Thanks for the diagnostics. Useful to know that having é in the user path causes the bug.

I found an earlier issue, so I'll close this issue as a duplicate of:
- #7789

**Closed by nbolton** 2024-11-15 13:04 UTC
Labels: bug, triage
