### ISSUE TITLE
Unnecessary take over of unused screen edges

### ISSUE THREAD

**Issue by SelfRef** [deskflow/deskflow#7799] opened 2024-10-23 12:36 UTC
### Project

Deskflow

### Deskflow version number

1.17.0.r125.gdfbd612 (latest from git at the moment)

### Build type

Local developer build (built it myself)

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [ ] Linux (X11)
- [X] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [X] I have reviewed the Wayland known issues and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [X] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

- Arch Linux with Gnome (latest)
- Windows 11 (latest)

### Deskflow configuration

- Arch Linux as server (AE-L-AZE-G14)
- Windows 11 as client configured as left side of server
![Screenshot From 2024-10-23 14-01-04](https://github.com/user-attachments/assets/cb05fc86-441e-458e-a717-2864c5d98756)

### What steps will reproduce the problem?

1. Run server & client
2. Drag mouse to the edge of the server where no client is configured
3. Any actions with mouse or keyboard are not recognized most of the time
    - First recording shows tries of opening Gnome menu, it's visible that libportal API is activated by Deskflow, even if no screens are configured on top and right edge.
    - Second recordings show tries of opening hidden Dash to Dock that requires "pushing" the bottom edge of the screen, with Deskflow active it's not working properly unless tried multiple times.

https://github.com/user-attachments/assets/4fd0cc96-afba-4d57-9cb4-dc9b0200de08

https://github.com/user-attachments/assets/e966007c-7ee1-4a61-9ca2-f0684e60dfea

### Log output

```shell
[2024-10-23T14:18:05] WARNING: language "" is unknown
[2024-10-23T14:18:05] WARNING: failed to convert layout lang code: ""
[2024-10-23T14:18:05] WARNING: language "" is unknown
[2024-10-23T14:18:05] WARNING: failed to convert layout lang code: ""
[2024-10-23T14:18:05] WARNING: language "" is unknown
[2024-10-23T14:18:05] WARNING: failed to convert layout lang code: ""
[2024-10-23T14:18:06] WARNING: language "" is unknown
[2024-10-23T14:18:06] WARNING: failed to convert layout lang code: ""
[2024-10-23T14:18:06] WARNING: language "" is unknown
[2024-10-23T14:18:06] WARNING: failed to convert layout lang code: ""
[2024-10-23T14:18:06] WARNING: language "" is unknown
[2024-10-23T14:18:06] WARNING: failed to convert layout lang code: ""
[2024-10-23T14:18:06] WARNING: language "" is unknown
[2024-10-23T14:18:06] WARNING: failed to convert layout lang code: ""
```

### Additional information

I'm not sure if it's a limitation of the Wayland libraries used by Deskflow, but it looks like Deskflow always tries to take over input when the cursor is on the edge of the screen, which is correct behavior for edges where client is configured but shouldn't happen for other edges.

**Comment by gabeklavans** [comment] 2024-10-23 16:37
Related, possibly duplicate of #7362

**Comment by nbolton** [comment] 2024-10-31 09:21
@SelfRef Would you mind determining if this is a duplicate of #7632 or a new issue?

**Comment by SelfRef** [comment] 2024-10-31 09:27
@nbolton From the bug's description and screen recording, I assume it's the same bug. On KDE it looks even more annoying than on Gnome.

**Comment by nbolton** [comment] 2024-10-31 09:32
Sounds good, I'll tenatively close it as a duplicate of #7632 but I notice that bug is closed by @sithlord48 as being tracked in discussion #7499. Thinking out loud, I wonder if we should keep the bugs open and simply use #7499 as an index to the open bugs. Just a thought.

**Closed by nbolton** 2024-10-31 09:32 UTC
Labels: bug, triage

**Comment by SelfRef** [comment] 2024-10-31 09:50
Technically, if the bug still occurs it shouldn't be closed (one of the duplicates at least), even if it's tracked elsewhere. This way, people can tract the bug's status and get notified when it's getting resolved (closed).

Also, looking at Wayland tracker discussion with all closed bugs would create a false impression, these problems are already resolved.

**Comment by nbolton** [comment] 2024-10-31 09:52
Inclined to agree, I'll discuss reopening the related Wayland bugs. We discuss this kind of thing on Matrix if you're interested in joining: https://matrix.to/#/#deskflow-dev:matrix.org

**Comment by sithlord48** [comment] 2024-10-31 11:28
> Also, looking at Wayland tracker discussion with all closed bugs would create a false impression, these problems are already resolved.

We have no control over what other projects do with bugs / issues we report

**Comment by SelfRef** [comment] 2024-10-31 11:53
@sithlord48 It's not about control, but monitoring the state. As long as the dependent issue in the other project is not resolved, it's misleading to close the issue in this project.

**Comment by sithlord48** [comment] 2024-10-31 12:36
But its not this projects issue id rather have one place then 100 issues ...

**Comment by gabeklavans** [comment] 2024-10-31 13:30
> But its not this projects issue id rather have one place then 100 issues ...

The prob is that every time someone experiences the bug, they’ll look for the issue in *this* repo, since that’s where they saw the bug surface, and not see any open issues, then either open a dupe or see the closed issues and get confused.

I completely agree that even if the problem is upstream, we should keep the issue open.

Additionally, technically, in a some cases someone could try to create a work around for Deskflow specifically. Don’t always have to wait for upstream to do it the “right” way if the bug is bad/stale enough.

**Comment by nbolton** [comment] 2024-11-01 11:56
I've placed the 'not our bug' tag to indicate it's probably an upstream issue. Still need to discuss with @sithlord48 but was swamped yesterday.
