### ISSUE TITLE
Mac[macos 15.1] to mac connection fails when firewall is enabled.

### ISSUE THREAD

**Issue by iamajohn** [deskflow/deskflow#7830] opened 2024-10-30 07:26 UTC
### Project

Deskflow

### Deskflow version number

1.17.0.152

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [ ] Windows
- [X] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

macOS 15.1 - macOS 12.7.6

### Deskflow configuration

macOS 15.1 server, two monitor , configured left
macOS 12.7.6 client, configured on right

### What steps will reproduce the problem?

1. Start Deskflow on both macbooks
2. Server (macOS 15 has two monitors)
3. Client (macOS 12.7.6) 
4. Allow Deskflow in firewall
5. Connection fails.

### Log output

```shell
[2024-10-30T12:46:40] INFO: starting core server process (desktop mode)
[2024-10-30T12:46:40] INFO: core config file: /Users/ajohn/Library/Preferences/Deskflow/deskflow-server.conf
[2024-10-30T12:46:40] INFO: running command: /Applications/Deskflow.app/Contents/MacOS/deskflow-server -f --no-tray --debug INFO --name Pf9 --enable-crypto --address :24800 -c /Users/ajohn/Library/Preferences/Deskflow/deskflow-server.conf --tls-cert /Users/ajohn/Downloads/deskflow.pem
[2024-10-30T12:46:40] NOTE: started server, waiting for clients
2024-10-30 12:46:40.859 deskflow-server[37276:1984818] starting cocoa loop
[2024-10-30T12:46:46] ERROR: standard exception on thread 0x00000004: std::exception
libc++abi: terminating due to uncaught exception of type std::exception: std::exception
[2024-10-30T12:46:46] WARNING: desktop process exited with error code: 6
[2024-10-30T12:46:47] INFO: starting core server process (desktop mode)
[2024-10-30T12:46:47] INFO: core config file: /Users/ajohn/Library/Preferences/Deskflow/deskflow-server.conf
[2024-10-30T12:46:47] INFO: running command: /Applications/Deskflow.app/Contents/MacOS/deskflow-server -f --no-tray --debug INFO --name Pf9 --enable-crypto --address :24800 -c /Users/ajohn/Library/Preferences/Deskflow/deskflow-server.conf --tls-cert /Users/ajohn/Downloads/deskflow.pem
[2024-10-30T12:46:47] NOTE: started server, waiting for clients
2024-10-30 12:46:47.846 deskflow-server[37279:1984967] starting cocoa loop
[2024-10-30T12:46:52] ERROR: standard exception on thread 0x00000004: std::exception
libc++abi: terminating due to uncaught exception of type std::exception: std::exception
[2024-10-30T12:46:52] WARNING: desktop process exited with error code: 6
[2024-10-30T12:46:52] INFO: stopping core process (desktop mode)
[2024-10-30T12:46:52] INFO: stopping core desktop process
```

### Additional information

Upon disabling firewall on macOS15 (server) the connection starts to work. Adding/allowing deskflow in firewall doesnt help!
Completely disabling firewall on server seems to establish connection.
Tried disabling SSL even that doesn't work, only disabling firewall seems to help.

**Comment by iamajohn** [comment] 2024-10-30 07:27
Not sure if this is related https://github.com/deskflow/deskflow/issues/7794

**Comment by nbolton** [comment] 2024-10-30 10:52
Hello, thanks for the bug report. I'm not seeing an SSL error in your log output, but I am seeing:
```
[2024-10-30T12:46:46] ERROR: standard exception on thread 0x00000004: std::exception
libc++abi: terminating due to uncaught exception of type std::exception: std::exception
``

What makes you suspect it's an SSL error?

**Comment by iamajohn** [comment] 2024-10-30 12:34
> Hello, thanks for the bug report. I'm not seeing an SSL error in your log output, but I am seeing:
> 
> ```
> [2024-10-30T12:46:46] ERROR: standard exception on thread 0x00000004: std::exception
> libc++abi: terminating due to uncaught exception of type std::exception: std::exception
> ```
> 
> What makes you suspect it's an SSL error?

The error i posted is not related to SSL, I was running into SSL error earlier which i have sorted.
I think i will have to correct the title in that case

**Comment by nbolton** [comment] 2024-10-30 12:35
Ok, I'll tentatively close this as a dupe of #7794 but let me know if it's a different issue.

**Closed by nbolton** 2024-10-30 12:35 UTC
Labels: bug, triage

**Comment by iamajohn** [comment] 2024-10-30 12:37
Okay
I am running on the latest macOS 15.1 as per your https://github.com/deskflow/deskflow/issues/7794#issuecomment-2446555304 its fixed on 15.1. But i don't think that is the case

**Comment by iamajohn** [comment] 2024-10-30 12:39
`[2024-10-30T17:59:44] DEBUG: opening configuration "/Users/ajohn/Library/Preferences/Deskflow/deskflow-server.conf"
[2024-10-30T17:59:44] DEBUG: configuration read successfully
[2024-10-30T17:59:44] DEBUG: screen shape: center=0,0 size=5568x1117 on 3 displays
[2024-10-30T17:59:44] DEBUG: starting watchSystemPowerThread
[2024-10-30T17:59:44] DEBUG: adopting new buffer
[2024-10-30T17:59:44] DEBUG: opened display
[2024-10-30T17:59:44] DEBUG: started watchSystemPowerThread
[2024-10-30T17:59:44] DEBUG: waiting for event loop
[2024-10-30T17:59:44] DEBUG: could not map hotkey id=ef14 mask=0000
[2024-10-30T17:59:44] NOTE: started server, waiting for clients
[2024-10-30T17:59:44] DEBUG: waiting for carbon loop
[2024-10-30T17:59:44] DEBUG: event queue is ready
[2024-10-30T17:59:44] DEBUG: signalling carbon loop ready
[2024-10-30T17:59:44] DEBUG: add pending events to buffer
[2024-10-30T17:59:44] DEBUG: starting carbon loop
[2024-10-30T17:59:44] DEBUG: add pending events to buffer
[2024-10-30T17:59:44] DEBUG: carbon loop ready
[2024-10-30T17:59:44] DEBUG: screen "Pf" shape changed
[2024-10-30T17:59:44] DEBUG: screen "Pf" shape changed
[2024-10-30T17:59:47] DEBUG: opening new socket: 00DFC000
[2024-10-30T17:59:47] ERROR: standard exception on thread 0x00000004: std::exception`

This ^ is the debug logs

**Comment by nbolton** [comment] 2024-10-30 12:50
Hmm, yeah some people are still seeing problems on macOS 15.1 and we're not sure why.

So, when you disable the firewall, this error goes away, yes?
```
[2024-10-30T17:59:47] ERROR: standard exception on thread 0x00000004: std::exception
```

If so, perhaps you could add your findings to #7794?

**Comment by iamajohn** [comment] 2024-11-05 10:30
https://github.com/deskflow/deskflow/issues/7794#issuecomment-2456804059
