### ISSUE TITLE
Fatal error - failed to cd up to profile root dir

### ISSUE THREAD

**Issue by Lyon88** [deskflow/deskflow#7995] opened 2024-12-20 11:18 UTC
### Project

Deskflow

### Deskflow version number

1.17.2.0

### Build type

Deskflow package (downloaded from Deskflow)

### Operating systems (OS)

- [X] Windows
- [ ] macOS
- [ ] Linux (X11)
- [ ] Linux (Wayland)
- [ ] BSD-derived
- [ ] Other (please specify)

### Wayland on Linux

- [ ] I have reviewed the Wayland [known issues](https://github.com/deskflow/deskflow/discussions/7499) and my issue is new
- [ ] I am not using Wayland on Linux

### Signing on macOS

- [ ] I have authorized the app to run on my Mac
- [ ] I am not using macOS

### Continuous build

- [ ] I have tried the latest continuous build and the issue persists
- [ ] I am unable to try the latest continuous build

### OS versions/distros

Windows 11

### What steps will reproduce the problem?

Start Deskflow

### Additional information

I installed the software in the root directory of the C drive, but when I opened it, I received this error message
![微信截图_20241220191602](https://github.com/user-attachments/assets/93077e49-6454-49b4-8421-289cc7242d3b)

**Comment by sithlord48** [comment] 2024-12-20 17:54
closing as duplicate of https://github.com/deskflow/deskflow/issues/7789

**Closed by sithlord48** 2024-12-20 17:54 UTC
Labels: bug, triage, unanswered
